name: force_update_helper
description: "A package for detecting if a forced app update is required"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.2
  pub_semver: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
